* Introduction

  Minimal (well, subjectively speaking) Emacs config in org-mode.
  It's started as a fork of Bruce Durling's [(https://github.com/otfrom/otfrom-org-emacs)[org-mode Emacs setup]
  in 2013. It's hard to find a clearer configuration for Emacs than org-mode.

  The real content is in [[./org/config.org][config.org]], which would probably be more
  interesting to read.

  This emacs config was set up to run on Mac OS X using the emacs from
  the very good [[http://emacsformacosx.com/][emacsformacosx.com]].

  If you want to use this I suggest you do the following:

  - create a emacs-config directory in your $HOME dir.
  - clone this repo in that directory
  - do a symbolic link from the clone to your .emacs.d directory

* Features

  Here are the things this emacs config gives examples for:

  - clojure support with cider
  - hippie expand
  - Using diminish to clean up a mode-line
  - Adding non-elpa files
  - Using multiple elpa package archives
  - Using color themes and custom fonts
  - very basic helm mode setup
  - magit & git gutter mode
  - paredit and rainbow delimiters
  - emacs on Mac OS X fixes
